[project]
name = "bme-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.9.0",
    "faiss-cpu>=1.12.0",
    "flake8>=7.3.0",
    "gunicorn>=23.0.0",
    "langchain>=0.3.27",
    "langchain-community>=0.3.30",
    "langchain-core>=0.3.78",
    "langchain-groq>=0.3.8",
    "langchain-huggingface>=0.3.1",
    "mypy>=1.18.2",
    "numpy>=2.3.3",
    "pillow>=11.3.0",
    "pypdf>=6.1.1",
    "pytesseract>=0.3.13",
    "pytest>=8.4.2",
    "pytest-cov>=7.0.0",
    "python-dotenv>=1.1.1",
    "requests>=2.32.5",
    "sentence-transformers>=5.1.1",
    "streamlit>=1.50.0",
    "unstructured[pdf]>=0.18.15",
]
